### ISSUE TITLE
cannot find module providing package entgo.io/ent/entc/integration/ent/hook

### ISSUE THREAD

**Issue by wahello** [flume/enthistory#16]
**Describe the bug**
When execute cmd
` go get github.com/flume/enthistory`
Error tip show 
`cannot find module providing package entgo.io/ent/entc/integration/ent/hook`
 

**Additional context**
```
go 1.20

require (
entgo.io/ent v0.12.3
)

```

**Comment by frisbm** [comment]
@wahello Thanks for bringing this to our attention! Didn't realize there was a breaking change in ent around hooks, should be resolved now in [v0.8.0](https://github.com/flume/enthistory/releases/tag/v0.8.0)
Will be closing as completed!
