### ISSUE TITLE
UUID support for schema ID field

### ISSUE THREAD

**Issue by mehmetcuneyit** [flume/enthistory#30]
I've been working with your extension and realized it lacks support for Google UUIDs as schema ID fields, which is something I need for my project. Before diving in to add this support myself, I wanted to check with you: Are there any known challenges or considerations I should be aware of? Would you have any advice or suggestions on integrating this feature?

**Comment by frisbm** [comment]
@mehmetcuneyit Thank for opening an issue! I don't entirely remember why I didn't implement UUID compatibility at the time, maybe because of the wide variety of UUID packages available, but with google's being the most popular it should be easy to just get at least that 1 in for now. I could probably knock it out pretty quickly today

**Comment by frisbm** [comment]
@mehmetcuneyit take a peak at #31 and see if this solves this for you! Specifically the `Residence` and generated `ResidenceHistory` Schemas and the updated tests

**Comment by mehmetcuneyit** [comment]
@frisbm thanks for the quick update. 

Considering the necessity to accommodate uuid for schema identification, it seems essential to adjust the updateByKey to handle uuid appropriately. I've devised a solution building upon your recent [PR31](https://github.com/flume/enthistory/pull/31). I'd be glad to contribute this enhancement by submitting a PR for uuid support in updateKey if you grant me temp access.

**Comment by frisbm** [comment]
You're more than welcome to open A PR merging into my branch, you'll just need to fork with the base as the branch from #31. if you open that up I'll close my PR in favor of yours.

**Comment by mehmetcuneyit** [comment]
@frisbm I've encountered two issues within my codespace, which includes over 100 schemas. Although I haven't pinpointed the exact cause, I suspect both issues are related to the entc templates. Notably, I couldn't replicate these problems using the examples provided in this repository and they might no be the common case. Here is my setup

``` go 
# entc.go
const schemaPath = "./schema"

func main() {
	if err := entc.Generate(
		schemaPath,
		&gen.Config{
			Schema:  "...",
			Target:  "...",			
			Package: "...",
			Features: []gen.Feature{								
				gen.FeaturePrivacy,				
				gen.FeatureEntQL,				
				gen.FeatureSnapshot,
				gen.FeatureSchemaConfig,								
				gen.FeatureModifier,
			},
		},		
		entc.Extensions(
			enthistory.NewHistoryExtension(
				enthistory.WithSchemaPath(schemaPath),
				enthistory.WithAuditing(),
				enthistory.WithHistoryTimeIndex(),
				enthistory.WithUpdatedBy("userId", enthistory.ValueTypeUUID),								
			),
		),
	); err != nil {
		log.Fatal("running ent codegen:", err)
	}
}

```

- I utilize a shared mixin that includes a custom ID field across my schemas.
   
```go
# sharedMixin.go
type SharedMixin struct {
	mixin.Schema
}

func (SharedMixin) Fields() []ent.Field {
	return []ent.Field{
		field.UUID("id", uuid.UUID{}).
			Default(uuid.New).
			Immutable(),		
		field.String("fieldA").
			NotEmpty(),
	         ...
	}
}

# schemaA.go
type SchemaA struct {
	ent.Schema
}

func (SchemaA) Mixin() []ent.Mixin {
	return []ent.Mixin{
		SharedMixin{},
	}
}
```


### 1. The issue in my codespace is the history table's ID field is set to generate as UUIDs, rather than integers.

For the history table, ID field is specifically excluded in both `schema.tmpl` and the checks within `enthistory.go`. This design choice seems to be based on allowing the default ID type to be determined by entc during code generation, as indicated in the [entc codegen process](https://github.com/ent/ent/blob/6631ed7172f9bd615c4812cb8508dc9bc8716112/entc/gen/graph.go#L60). 

 When calling `next.Generate(graph)` in `enthistory.go`, the IDType set by enthistory overrides the default IDType in entc templates. This leads to the history table's ID field being generated as UUIDs, diverging from entc's usual integer ID type.

However, activating the auditing feature causes issues because the history table's ID type is now UUID.

- auditing.tmpl
```
func ({{ $h.Receiver }} *{{ $h.Name }}) Diff(history *{{ $h.Name }}) (*HistoryDiff[{{ $h.Name }}], error) {

...
  {{ $h.Receiver }}Unix, historyUnix := {{ $h.Receiver }}.HistoryTime.Unix(), history.HistoryTime.Unix()
      {{ $h.Receiver }}Older := {{ $h.Receiver }}Unix < historyUnix || ({{ $h.Receiver }}Unix == historyUnix && {{ $h.Receiver }}.ID < history.ID)
      historyOlder := {{ $h.Receiver }}Unix > historyUnix || ({{ $h.Receiver }}Unix == historyUnix && {{ $h.Receiver }}.ID > history.ID)
...
```

And, UUIDs as IDs in the history table disrupt this due to their non-sequential nature, affecting the function's ability to accurately determine entry order. Preferably, UUIDs should not be used for history table IDs.

**As a workaround,**


If IDType is explicitly set to int in the entc configuration, then the history table's IDs will be generated as integers.
```go
...
  &gen.Config{
  ...
      IDType: &field.TypeInfo{Type: field.TypeInt},
  ...
 }
...
```

### 2. The template header invocation is incorrectly selecting the wrong UUID package.

- historyFromMutation.tmpl
```
... 
{{ define "historyFromMutation" }}
// Code generated by enthistory, DO NOT EDIT.
	{{ $pkg := base $.Config.Package }}
	{{ template "header" $ }}
...
```

In my codespace, the generated `history_from_mutation.go` file

```
...
import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent"
        "github.com/gofrs/uuid"
         "github.com/flume/enthistory"
)
...
````

The `gofrs UUID` package, an indirect dependency of one of the project's packages, is being imported instead of the `google UUID` package.

**As a solution,**

I directly specify the imports in the `historyFromMutation.tmpl` file.

**Comment by frisbm** [comment]
@mehmetcuneyit Got your PR merged into mine and I think i got those two issues addressed, you can see the commit with the changes without all the codegen [here](https://github.com/flume/enthistory/pull/31/commits/274377d278c426d4051e31a5c200c3e8545351a4)

Give the latest updates on the branch a try and see if everything is working with your setup

For the first issue, I was able to update the auditing codegen to account for UUIDs throughout without needing to force the history tables to use int Ids.

For the second one, I just needed to refine the import pattern to make sure all the correct imports were making it into the file. The `"github.com/gofrs/uuid"` import was being pulled in because entc runs goformat at the end of the codegeneration and goformat just makes a best guess when imports are missing.

**Comment by mehmetcuneyit** [comment]
@frisbm 

 - I don't have a specific need for using UUIDs in the history table, so I'd rather conserve space. 

Switching the history ID field to UUID could lead to concerns regarding table size, especially in scenarios where frequent modifications occur. This is because the size of the history table for each schema could significantly increase.

Taking a single schema with 1M entries in the history table as an example, the storage requirement using an integer ID would be about `1M x 4 bytes = 4 million bytes (~4MB)`, whereas using UUIDs would increase this to `1M x 16 bytes =16 million bytes (~16MB)`, resulting in an additional ~11.45MB of space for just one history table. Considering this across 100 schemas, the total additional space required would be:

```11.45MB * 100 = 1145MB (or ~ 1.12GB)```

This substantial increase in space consumption could be problematic in my scenario, suggesting the necessity for an option within entc configuration to allow forcing the use of integer IDs.

Regarding the second solution, it worked excellently.

**Comment by frisbm** [comment]
oh my fault, i think i misunderstood the first issue, i can back out that change and use the default IDs and just make the necessary fixes to for them directly for the auditing and diffing

**Comment by frisbm** [comment]
@mehmetcuneyit Got it all sorted out! You were right, looks like [entc was making an assumption](https://github.com/ent/ent/blob/6631ed7172f9bd615c4812cb8508dc9bc8716112/entc/gen/graph.go#L191) in the graph generation that if there was a common ID specified and only one kind was used it would assume that all models would receive that ID, a little strange. I was able to set the history IDs to Int to avoid that. Latest changes are up on the PR

**Comment by mehmetcuneyit** [comment]
@frisbm With the recent updates, I can verify that it now creates history tables with an integer ID field automatically, eliminating the need for manual entc configuration. Thank you for your dedication. I plan to rigorously test this new feature over the coming weeks and will provide feedback if I encounter any specific issues. Thanks once more.
