### ISSUE TITLE
Schema generation fails for Edge schemas without dedicated ID field

### ISSUE THREAD

**Issue by viv-dev** [flume/enthistory#43]
When defining an edge schema like this (taken from https://entgo.io/docs/schema-edges/#edge-schema):
```golang
// Like holds the edge schema definition for the Like edge.
type Like struct {
    ent.Schema
}

func (Like) Annotations() []schema.Annotation {
    return []schema.Annotation{
        field.ID("user_id", "tweet_id"),
    }
}

// Fields of the Like.
func (Like) Fields() []ent.Field {
    return []ent.Field{
        field.Time("liked_at").
            Default(time.Now),
        field.Int("user_id"),
        field.Int("tweet_id"),
    }
}

// Edges of the Like.
func (Like) Edges() []ent.Edge {
    return []ent.Edge{
        edge.To("user", User.Type).
            Unique().
            Required().
            Field("user_id"),
        edge.To("tweet", Tweet.Type).
            Unique().
            Required().
            Field("tweet_id"),
    }
}
```

> NOTE: that we want to store additional metadata regarding the relationship in this table - more than what is added in this example

Running ent generation with the enthistory extension added hits a nil dereference error when trying to extract the ID type at this point in `enthistory.go`:

```golang
// enthistory.go
func (h *HistoryExtension) generateHistorySchemas(next gen.Generator) gen.Generator {
    .
    .
    .


	var IdType *field.TypeInfo
	for _, node := range g.Nodes {
		if schema.Name == node.Name {
			IdType = node.ID.Type
		}
	}
    .
    .
    .
}
```

Resulting in the following error:

```bash
Exception has occurred: panic
"runtime error: invalid memory address or nil pointer dereference"
```

The `entc.go` file used was this:

```golang
//go:build ignore

package main

import (
	"log"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"github.com/flume/enthistory"
)

func main() {
	mpConfig := &gen.Config{
		Target: "./gen",
	}

	if err := entc.Generate("./schema",
		mpConfig,
		entc.Extensions(
			enthistory.NewHistoryExtension(
				enthistory.WithAuditing(),
			),
		),
	); err != nil {
		log.Fatal("running ent codegen:", err)
	}
}

```

**Comment by frisbm** [comment]
@viv-dev Thanks for opening this issue. It looks like you're using an older version of ent and i would recommend upgrading. That being said I did test your example in the latest version and sure enough there are issues there as well. This looks to be the bit thats causing the failure in enthistory
```go
func (Like) Annotations() []schema.Annotation {
    return []schema.Annotation{
        field.ID("user_id", "tweet_id"),
    }
}
```
This is my first time coming across the field schema annotations so I never accounted for them but I can do some research into how ent handles them and build out the necessary paths it.

**Comment by frisbm** [comment]
@viv-dev I'm gonna close this issue for now, the lack of ID() methods on the ent generated models makes it the too difficult considering a user can put any number of fields in the `field.ID(...)` annotation. It's definitely possible but the juice doesn't feel worth the squeeze in this case when users could handle this effectively the same with generated ID's and edges instead
