### ISSUE TITLE
Support for excluding specific actions from table history  via annotations/options

### ISSUE THREAD

**Issue by mehmetcuneyit** [flume/enthistory#45]
I would like to be able to disable history on certain hooks ( one or two of Create/Update/Delete) for a particular table. 

My objective is to prevent the history tables from being populated with create/delete actions but keeping update actions. I'm looking for a way to exclude these actions, ideally through some form of annotation or options.

**Comment by frisbm** [comment]
Hey again @mehmetcuneyit I should be able to implement this pretty easily. Are you looking at this as an option per schema or as a global option?

**Comment by mehmetcuneyit** [comment]
A hybrid approach seems promising for the long term, but for the near term, I'm leaning towards a per-schema option. Please let me know if there's any way I can assist or contribute to expedite the process.

**Comment by frisbm** [comment]
@mehmetcuneyit PR is up for this, should be in and released today
