### ISSUE TITLE
Transaction issue when integrating with entgql

### ISSUE THREAD

**Issue by joemocquant** [flume/enthistory#64]
**Describe the bug**

When integrating with `entgql` and using [Transactional Mutation](https://entgo.io/docs/tutorial-todo-gql-tx-mutation):
```
srv := handler.New(resolver.NewSchema(entClient))
srv.Use(entgql.Transactioner{TxOpener: entClient})
srv.Use(entgql.Transactioner{TxOpener: entClient})
```

An entity configured with `enthistory` getting a mutation is throwing an error:
`sql: transaction has already been committed or rolled back`

**To Reproduce**
WIP

**Expected behavior**
Operations on history tables should not be interfering with entity mutations.

**Additional context**
sql driver used: pgx (this might not be relevant).

Before diving any further, is this a known limitation of using `enthistory` with `entgql`?

**Comment by joemocquant** [comment]
This is not an issue. I was able to solve it. Please delete this issue.

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via here  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app/) Regards
