### ISSUE TITLE
Code Gen does not use set Schema Path 

### ISSUE THREAD

**Issue by MatthewBehnke** [flume/enthistory#7]
**Describe the bug**
When schemas exist in an alternate directory other than /schema like /pkg/database/models. Enthistory fails to write history tables to the set schema directory. 

**To Reproduce**
```
//go:build ignore
// +build ignore

package main

import (
	"log"

	"entgo.io/ent/entc"
	"entgo.io/ent/entc/gen"
	"github.com/flume/enthistory"
)

func main() {
	if err := entc.Generate("./pkg/database/models", &gen.Config{ 
		Package: ".../pkg/database/ent",
		Target:  "./pkg/database/ent",
		Features: []gen.Feature{
			gen.FeatureLock,
			gen.FeatureUpsert,
		},
	},
		entc.Extensions(
			enthistory.NewHistoryExtension(
				enthistory.WithUpdatedBy("userUUID", enthistory.ValueTypeString),
				enthistory.WithAuditing(),
			),
		),
	); err != nil {
		log.Fatal("running ent codegen:", err)
	}
}
```

**Expected behavior**
Expect Enthistory to use the set schema directory to write the new history tables to. 

Note I am not even sure ent exposes the schema directory to use so this might not be possible.

**Comment by frisbm** [comment]
@MatthewBehnke thanks for bringing to our attention! I'm out of country for the next week-ish but can work on a solution for this when I'm back
